### ISSUE TITLE
页面刷新好像也是404

### ISSUE THREAD

**Issue by Lee981265** [Mitscherlich/hexo-theme-amber#5]
希望大佬解决一下

**Comment by Mitscherlich** [comment]
你好，请问具体是文章页？还是某个自定义页面？方便的话提供一下复现方法？

**Comment by Lee981265** [comment]
都会

**Comment by Lee981265** [comment]
https://lee981265.coding.me/  这是我的地址你点点看

**Comment by Lee981265** [comment]
先点击一篇文章进去再刷新页面

**Comment by Mitscherlich** [comment]
我这边访问似乎没有问题？

![screenshot](https://user-images.githubusercontent.com/19310241/51239484-7b99de80-19b4-11e9-8b87-9a8f7ac501e0.png)

国内 unpkg 有些慢的话可以换成 jsdelivr

**Comment by Lee981265** [comment]
你的好像是刷新就跳转到主页了

**Comment by Mitscherlich** [comment]
如果需要像 hexo 那样提供每一个页面的静态文件，可以通过在 hexo 根目录下的 _config.yml 中设置文章永久链接 (permalink) 来实现：

```yaml
# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://your.domain
root: /
permalink: articles/: title/ # vue-router 实际对应的路径是这样的形式
permalink_defaults:
```
